### ISSUE TITLE
Simple test example

### ISSUE THREAD

**Issue by cpipero** [SoftingIndustrial/XMItoNodeset#1]
I just tried the attached xmi file with the following command:

`XMItoNodeset.exe /xmi "sampleModel.xml" /nodeset "sampleNodes.xml"`

but the generated xml only contains the default UA nodes
`<?xml version="1.0" encoding="UTF-8"?>`
`<UANodeSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ``xmlns:xsd="http://www.w3.org/2001/XMLSchema" LastModified="2016-11-30T09:33:33.1336892Z" ``xmlns="http://opcfoundation.org/UA/2011/03/UANodeSet.xsd">`
`  <NamespaceUris>`
`    <Uri>http://industrial.softing.com/XMItoNodeset</Uri>`
`  </NamespaceUris>`
`  <Aliases>`
`    <Alias Alias="Boolean">i=1</Alias>`
`    <Alias Alias="SByte">i=2</Alias>`
`    <Alias Alias="Byte">i=3</Alias>`
`    <Alias Alias="Int16">i=4</Alias>`
`    <Alias Alias="UInt16">i=5</Alias>`
`    <Alias Alias="Int32">i=6</Alias>`
`    <Alias Alias="UInt32">i=7</Alias>`
`    <Alias Alias="Int64">i=8</Alias>`
`    <Alias Alias="UInt64">i=9</Alias>`
`    <Alias Alias="Float">i=10</Alias>`
`    <Alias Alias="Double">i=11</Alias>`
`    <Alias Alias="String">i=12</Alias>`
`    <Alias Alias="ByteString">i=15</Alias>`
`    <Alias Alias="Structure">i=22</Alias>`
`    <Alias Alias="BaseDataType">i=24</Alias>`
`    <Alias Alias="Enumeration">i=29</Alias>`
`    <Alias Alias="Organizes">i=35</Alias>`
`    <Alias Alias="HasModellingRule">i=37</Alias>`
`    <Alias Alias="HasEncoding">i=38</Alias>`
`    <Alias Alias="HasDescription">i=39</Alias>`
`    <Alias Alias="HasTypeDefinition">i=40</Alias>`
`    <Alias Alias="HasSubtype">i=45</Alias>`
`    <Alias Alias="HasProperty">i=46</Alias>`
`    <Alias Alias="HasComponent">i=47</Alias>`
`    <Alias Alias="PropertyType">i=68</Alias>`
`    <Alias Alias="Mandatory">i=78</Alias>`
`    <Alias Alias="Optional">i=80</Alias>`
`    <Alias Alias="OptionalPlaceholder">i=11508</Alias>`
`    <Alias Alias="MandatoryPlaceholder">i=11510</Alias>`
`    <Alias Alias="DefaultVariableRefType">i=47</Alias>`
`    <Alias Alias="DefaultObjectRefType">i=47</Alias>`
`  </Aliases>`
`</UANodeSet>`

If possible, please provide a working example. This project is a really good idea.
Thanks
[sampleModel.xml.txt](https://github.com/SoftingIndustrial/XMItoNodeset/files/622047/sampleModel.xml.txt)

**Comment by thomasrummel** [comment]
I have added a simple example to the Examples/SoftingDiagnostics folder.

It includes the Enterprise Architect file and the XMI file exported from EA.

If you execute the StartSoftingDiagnostics.bat file it creates the nodeset file with the debug build.
